modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ghost_boats"
version = "${version}"
displayName = "Ghost Boats"
authors = "GuiTaek"
description = '''
Show other boat racers as ghost boats.
'''
logoFile = "assets/ghost_boats/icon.png"

[[dependencies.ghost_boats]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ghost_boats]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ghost_boats]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "ghost_boats.mixins.json"
